// <auto-generated />
namespace NRepository.EntityFramework.Tests
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddedClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedClass));
        
        string IMigrationMetadata.Id
        {
            get { return "201404151921374_AddedClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
