// <auto-generated />
namespace NRepository.EntityFramework.Tests
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StoredProc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StoredProc));
        
        string IMigrationMetadata.Id
        {
            get { return "201507151838011_StoredProc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
